info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /order/:
    get:
      description: View for creating and getting pizza orders
      operationId: order_list
      tags:
      - order
    post:
      description: View for creating and getting pizza orders
      operationId: order_create
      tags:
      - order
  /order/{Order_ID}:
    delete:
      description: View for deleting and getting single pizzas
      operationId: order_delete
      parameters:
      - in: path
        name: Order_ID
        required: true
        schema:
          description: ''
          title: Order ID
          type: string
      tags:
      - order
    get:
      description: View for deleting and getting single pizzas
      operationId: order_read
      parameters:
      - in: path
        name: Order_ID
        required: true
        schema:
          description: ''
          title: Order ID
          type: string
      tags:
      - order
servers:
- url: ''
