# Generated by Django 3.2.6 on 2021-08-17 01:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('Hawaii', 'Hawaii'), ('Regina', 'Regina'), ('Quattro-Formaggi', 'Quattro-Formaggi')], default='Hawaii', max_length=16)),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium')], default='Medium', max_length=6)),
                ('crust', models.CharField(choices=[('Thin', 'Thin')], default='Thin', max_length=4)),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(30000))),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
