# Generated by Django 3.2.6 on 2021-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('Hawaii', 'Hawaii'), ('Regina', 'Regina'), ('Quattro-Formaggi', 'Quattro-Formaggi')], default='Hawaii', max_length=16)),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium')], default='Medium', max_length=6)),
                ('crust', models.CharField(choices=[('Thin', 'Thin')], default='Thin', max_length=5)),
                ('table_number', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
