# Generated by Django 3.2.6 on 2021-08-16 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='crust',
            field=models.CharField(choices=[('Thin', 'Thin')], default='Thin', max_length=4),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='table_number',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(30000)),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
